---
abstract: 'Automatic JS/CSS minifier & compressor for Mojolicious'
author:
  - 'Masanori Ohgita (http://ohgita.info)'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-StaticCompressor
provides:
  Mojolicious::Plugin::StaticCompressor:
    file: lib/Mojolicious/Plugin/StaticCompressor.pm
    version: v0.0.2
requires:
  CSS::Minifier: 0
  Encode: 0
  File::Slurp: 0
  FindBin: 0
  JavaScript::Minifier: 0
  Module::Build: 0
  Mojo::Util: 0
  Mojolicious: 3.88
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 1.08
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2
